services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    user: root
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Passw1rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data